# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook
---
- name: Install dependencies
  hosts: proxy
  tasks:
    - name: install Certbot
      package:
        state: latest
        name: certbot
    - name: install Trojan
      command: sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/trojan-gfw/trojan-quickstart/master/trojan-quickstart.sh)"
- name: setup Trojan
  hosts: proxy
  tasks:
    - name: initialize SSL credential
      command: sudo certbot certonly --standalone
    - name: config Trojan
      copy:
        dest: /usr/local/etc/trojan/config.json
        content: |
          {
              "run_type": "server",
              "local_addr": "0.0.0.0",
              "local_port": 443,
              "remote_addr": "127.0.0.1",
              "remote_port": 80,
              "password": [
                  "Lovestory@hk"
              ],
              "log_level": 1,
              "ssl": {
                  "cert": "/etc/letsencrypt/live/aliyun-sg-tunnel.magicbox10.com/fullchain.pem",
                  "key": "/etc/letsencrypt/live/aliyun-sg-tunnel.magicbox10.com/privkey.pem",
                  "key_password": "",
                  "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
                  "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
                  "prefer_server_cipher": true,
                  "alpn": [
                      "http/1.1"
                  ],
                  "alpn_port_override": {
                      "h2": 81
                  },
                  "reuse_session": true,
                  "session_ticket": false,
                  "session_timeout": 600,
                  "plain_http_response": "",
                  "curves": "",
                  "dhparam": ""
              },
              "tcp": {
                  "prefer_ipv4": false,
                  "no_delay": true,
                  "keep_alive": true,
                  "reuse_port": false,
                  "fast_open": false,
                  "fast_open_qlen": 20
              },
              "mysql": {
                  "enabled": false,
                  "server_addr": "127.0.0.1",
                  "server_port": 3306,
                  "database": "trojan",
                  "username": "trojan",
                  "password": "",
                  "cafile": ""
              }
          }
    - name: start Trojan
      command: sudo systemctl restart trojan.service
